### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by Luthaf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please make this change using a PR created from a branch on your fork. All branches on the main repo deploy as soon as their builds pass.

**Comment by Luthaf** [comment]
> Please make this change using a PR created from a branch on your fork. All branches on the main repo deploy as soon as their builds pass.

OK, did not knew that! Why is it for?

**Comment by jakirkham** [comment]
Also, for reference, one needs `python` as a build dependency for Windows or one must use the `vc` package.

xref: https://github.com/conda-forge/staged-recipes/wiki/VC-features

**Comment by Luthaf** [comment]
Thank you, that was the documentation I was looking for!

**Pull request closed without merging**
