### PR TITLE
V0.9.2

### PR DESCRIPTION
**Pull request by Luthaf**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Luthaf** [comment]
Appveyor build seems to get stuck compiling the tests. No idea why ...

**Comment by Luthaf** [comment]
> Appveyor build seems to get stuck compiling the tests. No idea why ...

For some reason, the build uses /GL for objects and /LTCG for linking the executables, which is multiple order of magnitude slower. I am not explicitly setting these flags, and using a local Windows VM with the same cmake version as appveyor do not set them either, so where do they come from?

It looks like a common issue in conda-forge repositories: 
- https://github.com/conda-forge/thrift-cpp-feedstock/issues/19
- https://github.com/conda-forge/nodejs-feedstock/commit/2b8cfe81d11e27bffcf17e0a82a01df22df178f2
- https://github.com/conda-forge/clangdev-feedstock/commit/13353def4ec7255a17bc9ad6bf26ad5005b6d7f1
- https://github.com/conda-forge/lastools-feedstock/commit/0fdf05e55a653fba5d06cb08d5db189562970f4c

@isuruf do you know what is setting these flags? Is it related to conda?

**Comment by Luthaf** [comment]
Found it, it is the compiler activation scripts that does it https://github.com/AnacondaRecipes/aggregate/blob/af6f001cdbe59e3a2958cb1e5fee7a2b79578229/vs2015/activate.bat#L41

**Comment by isuruf** [comment]
@conda-forge-admin, rerender.

**Comment by Luthaf** [comment]
I'll do a rerender locally and disable /GL

**Comment by Luthaf** [comment]
Without /GL, build takes 12min, with /GL build takes 1h10min !

**Pull request merged**
